---
title: "Stimuli selection from SPP"
author: '[Guillermo Montero-Melis](http://www.biling.su.se/montero_melis_guillermo)'
date: '`r as.character(format(Sys.Date(), format="%d/%m/%Y"))`'
output:
  html_document:
    depth: 2
    number_sections: yes
    theme: default
    toc: yes
---


```{r setup, include=FALSE}
library("knitr")
library("ggplot2")
# library(GGally)
library("dplyr")
library("tidyr")
# library(lme4)
knitr::opts_chunk$set(echo = TRUE)
```


Introduction
===========


Data set from SPP
================

Load data
---------

```{r}
d <- read.csv("stimuli/spp_assoc-related_181205.csv")
head(d)
```

Process data
------------

Correct some typos in the data coding.

`Relation1` has typos

```{r}
# Correct some typos in the data coding
# Relation 1
levels(d$Relation1)
table(d$Relation1)
rel1 <- as.character(d$Relation1)
rel1 <- sub("antonymn", "antonym", rel1)
rel1 <- sub("unclassifed", "unclassified", rel1)
rel1 <- sub("Instrument", "instrument", rel1)
d$Relation1 <- factor(rel1)
levels(d$Relation1)
table(d$Relation1)
```

`POS` sometimes counts the same category as different only because POS are listed
in different order. Unless the ordering actually has a meaning? E.g., primary
POS, seconday POS, etc. in that order?

```{r}
# POS
levels(d$POS)
```



Descriptives
-----------

```{r}
# Reshape to long format
d_long_num <- d %>%
  select(- c(POS, Relation1 : Relation2)) %>%
  gather(key = "variable", value = "value", Length : LDT.1200ms.Acc.Priming)
kable(head(d_long_num))
d_long_factor <- d %>%
  select(TargetWord, Prime, POS, Relation1 : Relation2) %>%
  gather(key = "variable", value = "value", POS, Relation1 : Relation2)
kable(head(d_long_factor))
```

```{r, fig.height = 16, fig.width = 12}
ggplot(d_long_num, aes(value)) + 
  geom_histogram(aes(y=..density..), colour="black", fill="white") +
  geom_density(alpha=.2, fill="#FF6666") +
  facet_wrap(~variable, scales = 'free') +
  theme(axis.text.y=element_blank())
```

```{r, fig.width = 10}
ggplot(d_long_factor, aes(x = value)) +
  geom_bar() +
  facet_wrap(~variable, scales = 'free') +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))
```

